version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-serverless
          command: 'sudo npm install -g serverless'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm-test
          command: npm test
      - run:
          name: npm-lint
          command: npm run lint
      - deploy:
          name: sls-deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sls deploy
              else
                echo "Not master branch so not deploying"
              fi
